apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  #volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  iscsi:
    # default port is 3260
    targetPortal: $(ISCSI_HOST)
    iqn: $(ISCSI_PSQL_IQN)
    lun: 1
    fsType: "ext4"
    readOnly: false
