apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # kube infrastructure
  - nfs-client-provisioner.yaml
  # infrastructure
  - postgresql.yaml
  - redis.yaml
  - mariadb.yaml
  - rabbitmq.yaml
  # wordpress
  - wordpress.yaml
  # backups
  - cron-backup.yaml
configMapGenerator:
  - name: nfs-config
    env: .env-nfs
  - name: redis-config
    files:
      - configs/redis.conf
  - name: site-config
    env: .env-sites
secretGenerator:
  - name: wordpress-secrets
    env: .env-wordpress
  - name: mysql-secrets
    env: .env-mysql
  - name: rabbitmq-secrets
    env: .env-rabbitmq
  - name: psql-secrets
    env: .env-psql
configurations:
  # maps what fields can have variable substitution used below
  - config.yaml
patchesStrategicMerge:
  # these files are built by ./build.sh
  - build/wordpress.yaml
  - build/nfs-client-provisioner.yaml
vars:
  # this should all exist in ENV files specified `key=value`
  # nfs
  - name: NFS_SERVER
    objref:
      name: nfs-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.NFS_SERVER
  - name: NFS_PATH
    objref:
      name: nfs-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.NFS_PATH
  # sites
  - name: DOMAIN_LOCAL
    objref:
      name: site-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DOMAIN_LOCAL
  - name: DOMAIN_1
    objref:
      name: site-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DOMAIN_1_JOHN
  - name: DOMAIN_2_WWW
    objref:
      name: site-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DOMAIN_2_WWW
  - name: DOMAIN_2
    objref:
      name: site-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DOMAIN_2
  - name: DOMAIN_3
    objref:
      name: site-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.DOMAIN_3
