apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # infrastructure
  - iscsi-postgres.yaml
  - iscsi-mariadb.yaml
secretGenerator:
  - name: generated-secrets
    env: .env-secret
configurations:
  # maps what fields can have variable substitution used below
  - ../config.yaml
vars:
  # this should all exist in ENV files specified `key=value`
  # iscsi
  - name: ISCSI_HOST
    objref:
      name: generated-secrets
      apiVersion: v1
      kind: Secret
  - name: ISCSI_SQL_IQN
    objref:
      name: generated-secrets
      apiVersion: v1
      kind: Secret
  - name: ISCSI_PSQL_IQN
    objref:
      name: generated-secrets
      apiVersion: v1
      kind: Secret
