apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # infrastructure
  - iscsi-postgres.yaml
  - iscsi-mariadb.yaml
configMapGenerator:
  - name: iscsi-config
    env: ../.env-iscsi
vars:
  # this should all exist in ENV files specified `key=value`
  # iscsi
  - name: ISCSI_HOST
    objref:
      name: iscsi-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.ISCSI_HOST
  - name: ISCSI_SQL_IQN
    objref:
      name: iscsi-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.ISCSI_SQL_IQN
  - name: ISCSI_PSQL_IQN
    objref:
      name: iscsi-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.ISCSI_PSQL_IQN
