kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
