# this file is edited and copied to deploy/ at build time to add environment variables
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
spec:
  template:
    spec:
      volumes:
        - name: nfs-client-root
          nfs:
            server: $NFS_SERVER
            path: "/$NFS_PATH"

